/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import database.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author User
 */
public class framekartustudi extends javax.swing.JFrame {
    private koneksi obj;
    public DefaultTableModel modelKRS;
     
    /**
     * Creates new form FrameUtama
     */
    public framekartustudi() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        obj = new koneksi();
        modelKRS = new DefaultTableModel();
        tableKRS.setModel(modelKRS);
        modelKRS.addColumn("ID KRS");
        modelKRS.addColumn("NIM");
        modelKRS.addColumn("KODE MATA KULIAH");
        modelKRS.addColumn("STATUS");
       
        tampilDataKRS();
    }

public void tampilDataKRS() {
   try {
            modelKRS.setRowCount(0);

            String query = "SELECT * FROM krs";
            try (PreparedStatement preparedStatement = obj.konek.prepareStatement(query);
                 ResultSet data = preparedStatement.executeQuery()) {
                while (data.next()) {
                    Object[] line = new Object[4];
                    line[0] = data.getString("id_krs");
                    line[1] = data.getString("nim");
                    line[2] = data.getString("kode_matakuliah");
                    line[3] = data.getString("status");
                    modelKRS.addRow(line);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdKrs = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        txtMataKuliah = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKRS = new javax.swing.JTable();
        txtStatus = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 182, 192));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("Id KRS");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("NIM");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setText("Kode Matakuliah");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setText("Status");

        txtIdKrs.setBackground(new java.awt.Color(255, 228, 255));

        txtNim.setBackground(new java.awt.Color(255, 228, 255));

        txtMataKuliah.setBackground(new java.awt.Color(255, 228, 255));

        jPanel2.setBackground(new java.awt.Color(255, 142, 142));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("FORM KRS (KARTU RENCANA STUDI)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(255, 206, 206));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 206, 206));
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 206, 206));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 206, 206));
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 206, 206));
        jButton5.setText("PRINT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tableKRS.setBackground(new java.awt.Color(253, 226, 222));
        tableKRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKRS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKRSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKRS);

        txtStatus.setBackground(new java.awt.Color(255, 228, 255));

        btnBack.setBackground(new java.awt.Color(255, 200, 200));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdKrs, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel5)))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMataKuliah, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(txtStatus))))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtIdKrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(txtMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton5)
                                    .addComponent(btnBack)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
           if (txtIdKrs.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "ID KRS Mahasiswa belum diisi");
               txtIdKrs.requestFocus();
           } else if (txtNim.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "NIM belum diisi");
               txtNim.requestFocus();
           } else if (txtMataKuliah.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Mata Kuliah belum diisi");
               txtMataKuliah.requestFocus(); 
           } else if (txtStatus.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Status belum diisi");
               txtStatus.requestFocus();
           } else {
               String sql = "insert into krs value('"+txtIdKrs.getText()+"','"+txtNim.getText()+"','"+txtMataKuliah.getText()+"','"+txtStatus.getText()+"')";
               obj.konek.createStatement().execute(sql);
               JOptionPane.showMessageDialog(this, "data berhasil disimpan");
           }
           tampilDataKRS();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
    if (txtIdKrs.getText().isEmpty() || txtNim.getText().isEmpty() ||
        txtMataKuliah.getText() .isEmpty() || txtStatus.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Silahkan isi semua data terlebih dahulu!");
    } else {
        // Bagian untuk INSERT
        String sqlInsert = "INSERT INTO krs (id_krs, nim,  kode_matakuliah, status) " +
                           "VALUES (?, ?, ?, ?)";
        PreparedStatement insertStmt = obj.konek.prepareStatement(sqlInsert);

        insertStmt.setString(1, txtIdKrs.getText());
        insertStmt.setString(2, txtNim.getText());
        insertStmt.setString(3, txtMataKuliah.getText());
        insertStmt.setString(4, txtStatus.getText());

        // Bagian untuk UPDATE
        String sqlUpdate = "UPDATE krs SET nim=?, kode_matakuliah=?, status=? WHERE id_krs=?";
        PreparedStatement updateStmt = obj.konek.prepareStatement(sqlUpdate);

        updateStmt.setString(1, txtIdKrs.getText());
        updateStmt.setString(2, txtNim.getText());
        updateStmt.setString(3, txtMataKuliah.getText());
        updateStmt.setString(4, txtStatus.getText());
       

        // Eksekusi query UPDATE
        int hasilUpdate = updateStmt.executeUpdate();

        // Eksekusi query INSERT jika tidak ada baris yang terupdate
        if (hasilUpdate == 0) {
            int hasilInsert = insertStmt.executeUpdate();

            if (hasilInsert > 0) {
                tampilDataKRS();
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data. Pastikan Kode yang dimasukkan benar.");
            }
        } else {
            tampilDataKRS();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
    // Mengecek apakah semua kolom input kosong
    if (txtIdKrs.getText().isEmpty() && txtNim.getText().isEmpty()
            && txtMataKuliah.getText().isEmpty() && txtStatus.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
        } else {
            // Menampilkan dialog konfirmasi sebelum menghapus
            int confirmDialogResult = JOptionPane.showConfirmDialog(this,
                    "Apakah Anda yakin ingin menghapus data?", "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION);

            // Jika pengguna mengonfirmasi untuk menghapus
            if (confirmDialogResult == JOptionPane.YES_OPTION) {
                // Query SQL untuk menghapus data dari tabel
                String sql = "DELETE FROM krs WHERE id_krs=?";
                
                // Menggunakan try-with-resources untuk PreparedStatement
                try (PreparedStatement hapus = obj.konek.prepareStatement(sql)) {
                    hapus.setString(1, txtIdKrs.getText());
                    
                    // Menjalankan query DELETE dan mendapatkan jumlah baris yang terpengaruh
                    int rowsAffected = hapus.executeUpdate();

                    // Jika ada baris yang terpengaruh, berarti data berhasil dihapus
                    if (rowsAffected > 0) {
                        tampilDataKRS();
                        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                    } else {
                        // Jika tidak ada baris yang terpengaruh, berarti data tidak ditemukan
                        JOptionPane.showMessageDialog(this, "Gagal menghapus data. Data tidak ditemukan.");
                    }
                }
            }
        }
    } catch (SQLException | HeadlessException e) {
        // Menangani kesalahan dan menampilkan pesan kesalahan kepada pengguna
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableKRSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKRSMouseClicked
  // TODO add your handling code here:
        int baris = tableKRS.getSelectedRow();
        String id_krs = tableKRS.getValueAt(baris, 0).toString();
        String nim = tableKRS.getValueAt(baris, 1).toString();
        String kode_matakuliah = tableKRS.getValueAt(baris, 2).toString();
        String status = tableKRS.getValueAt(baris, 3).toString();
        txtIdKrs.setText(id_krs);
        txtNim.setText(nim);
        txtMataKuliah.setText(kode_matakuliah);
        txtStatus.setText(status);
    }//GEN-LAST:event_tableKRSMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
txtIdKrs.setText("");
txtNim.setText("");
txtMataKuliah.setText("");
txtStatus.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String path = ".\\src\\Report\\ReportKRS.jasper";
        try {
        // Mengatur koneksi database (gantilah parameter koneksi dengan yang sesuai)
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/apk_krs", "root", "");

        // Mengisi laporan dengan data dari database
        JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);

        // Menampilkan laporan menggunakan JasperViewer
        JasperViewer jviewer = new JasperViewer(jprint, false);
        jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jviewer.setVisible(true);

        // Menutup koneksi database setelah selesai
        conn.close();
     } catch (JRException | SQLException e) {
        // Menangkap dan menampilkan exception
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
new frameUtama().setVisible(true);
dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framekartustudi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framekartustudi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framekartustudi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framekartustudi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framekartustudi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKRS;
    private javax.swing.JTextField txtIdKrs;
    private javax.swing.JTextField txtMataKuliah;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
